Fix securyt vulnerabilities
pagarme/woocommerce-beta pull request #61
Opened 2021-08-30 19:13 UTC by danielmadu

| Questions     | Answers
| ------------- | -------------------------------------------------------
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-275
| **What?**         | Fixed securyt issues

2021-08-31 13:49 UTC, yanpantoja requested changes

2021-08-31 13:49 UTC, yanpantoja commented on src/Helper/Utils.php
> +use Woocommerce\Pagarme\Concrete\WoocommerceCoreSetup as CoreSetup;
Fiquei na dúvida se essa importação está sendo usada, ela está?

2021-08-31 13:49 UTC, yanpantoja commented on src/Helper/Utils.php
> +        if(!hash_equals($signature, hash_hmac('sha256', $post_data, $settings->get_secret_key()))) {
Seguindo o padrão PSR, faltou só um espaço aqui depois do if ()

2021-09-10 21:38 UTC, netorodrigues commented on templates/checkout/2-cards-item.php
> +$ref1              = sha1(random_int(1, 1000));
A compra nas formas de pagamento onde passamos a usar o `sha1` em vez do `md5 ` foi testada e continua funcional?

2021-09-14 19:36 UTC, danielmadu commented on templates/checkout/2-cards-item.php
> +$ref1              = sha1(random_int(1, 1000));
Sim, foi testada e continua funcionando normalmente

2021-09-15 14:27 UTC, netorodrigues submitted a review, later dismissed

2021-09-15 22:22 UTC, yanpantoja approved these changes

2021-09-15 22:52 UTC, netorodrigues approved these changes

2021-09-16 18:27 UTC, merged